[package]
name = "multi"
version = "0.1.0"
authors = ["Tom <tom@contextfree.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "0.3"

[[bin]]
name = "multi"
path = "multi.rs"
